import 'package:flutter/material.dart';

class AzkarCategoryEntity {
  final String name;
  final List<AzkarEntity> azkarList;

  AzkarCategoryEntity({required this.name, required this.azkarList});
  final Map<String, IconData> categoryIcons = {
    "أذكار الصباح": Icons.wb_sunny,
    "أذكار المساء": Icons.nights_stay,
    "أذكار الاستيقاظ من النوم": Icons.alarm,
    "دعاء لبس الثوب": Icons.checkroom,
    "دعاء لبس الثوب الجديد": Icons.new_releases,
    "ما يقول إذا وضع الثوب": Icons.checkroom,
    "دعاء دخول الخلاء": Icons.wc,
    "دعاء الخروج من الخلاء": Icons.wc_outlined,
    "الذكر قبل الوضوء": Icons.opacity,
    "الذكر بعد الفراغ من الوضوء": Icons.water_drop,
    "الذكر عند الخروج من المنزل": Icons.exit_to_app,
    "الذكر عند دخول المنزل": Icons.home,
    "دعاء الذهاب إلى المسجد": Icons.directions_walk,
    "دعاء دخول المسجد": Icons.meeting_room,
    "دعاء الخروج من المسجد": Icons.exit_to_app,
    "أذكار الآذان": Icons.access_time,
    "دعاء الاستفتاح": Icons.menu_book,
    "دعاء الركوع": Icons.format_align_center,
    "دعاء الرفع من الركوع": Icons.vertical_align_top,
    "دعاء السجود": Icons.south,
    "دعاء الجلسة بين السجدتين": Icons.pan_tool,
    "دعاء سجود التلاوة": Icons.book,
    "التشهد": Icons.how_to_reg,
    "الصلاة على النبي بعد التشهد": Icons.favorite,
    "الدعاء بعد التشهد الأخير قبل السلام": Icons.mosque,
    "الأذكار بعد السلام من الصلاة": Icons.book_online,
    "دعاء صلاة الاستخارة": Icons.lightbulb,
    "أذكار النوم": Icons.bedtime,
    "الدعاء إذا تقلب في الليل": Icons.nightlight_round,
    "دعاء الفزع في النوم و من بلي بالوحشة": Icons.warning,
    "ما يفعل من رأى الرؤيا أو الحلم في النوم": Icons.visibility,
    "دعاء قنوت الوتر": Icons.waves,
    "الذكر عقب السلام من الوتر": Icons.book,
    "دعاء الهم والحزن": Icons.sentiment_dissatisfied,
    "دعاء الكرب": Icons.report_problem,
    "دعاء لقاء العدو و ذي السلطان": Icons.shield,
    "الدعاء على العدو": Icons.block,
    "ما يقول من خاف قوما": Icons.warning,
    "دعاء من أصابه وسوسة في الإيمان": Icons.psychology,
    "دعاء قضاء الدين": Icons.account_balance,
    "دعاء الوسوسة في الصلاة و القراءة": Icons.psychology_alt,
    "دعاء من استصعب عليه أمر": Icons.help,
    "ما يقول ويفعل من أذنب ذنبا": Icons.do_not_disturb,
    "دعاء طرد الشيطان و وساوسه": Icons.cancel,
    "الدعاء حينما يقع ما لا يرضاه أو غلب على أمره": Icons.warning_amber,
    "ﺗﻬنئة المولود له وجوابه": Icons.child_friendly,
    "ما يعوذ به الأولاد": Icons.shield_moon,
    "الدعاء للمريض في عيادته": Icons.local_hospital,
    "فضل عيادة المريض": Icons.health_and_safety,
    "دعاء المريض الذي يئس من حياته": Icons.sick,
    "تلقين المحتضر": Icons.airline_seat_flat_angled,
    "دعاء من أصيب بمصيبة": Icons.sentiment_very_dissatisfied,
    "الدعاء عند إغماض الميت": Icons.remove_circle_outline,
    "الدعاء للميت في الصلاة عليه": Icons.account_balance_outlined,
    "الدعاء للفرط في الصلاة عليه": Icons.account_box,
    "دعاء التعزية": Icons.support,
    "الدعاء عند إدخال الميت القبر": Icons.account_circle,
    "الدعاء بعد دفن الميت": Icons.landscape,
    "دعاء زيارة القبور": Icons.place,
    "دعاء الريح": Icons.air,
    "دعاء الرعد": Icons.thunderstorm,
    "من أدعية الاستسقاء": Icons.cloud,
    "الدعاء إذا نزل المطر": Icons.grain,
    "الذكر بعد نزول المطر": Icons.umbrella,
    "من أدعية الاستصحاء": Icons.thermostat,
    "دعاء رؤية الهلال": Icons.nights_stay,
    "الدعاء عند إفطار الصائم": Icons.restaurant,
    "الدعاء قبل الطعام": Icons.restaurant_menu,
    "الدعاء عند الفراغ من الطعام": Icons.dining,
    "دعاء الضيف لصاحب الطعام": Icons.people,
    "التعريض بالدعاء لطلب الطعام أو الشراب": Icons.food_bank,
    "الدعاء إذا أفطر عند أهل بيت": Icons.home_work,
    "دعاء الصائم إذا حضر الطعام ولم يفطر": Icons.no_food,
    "ما يقول الصائم إذا سابه أحد": Icons.mood_bad,
    "الدعاء عند رؤية باكورة الثمر": Icons.emoji_food_beverage,
    "دعاء العطاس": Icons.health_and_safety,
    "ما يقال للكافر إذا عطس فحمد الله": Icons.info,
    "الدعاء للمتزوج": Icons.favorite,
    "دعاء المتزوج و شراء الدابة": Icons.shopping_cart,
    "الدعاء قبل إتيان الزوجة": Icons.bed,
    "دعاء الغضب": Icons.emoji_emotions,
    "دعاء من رأى مبتلى": Icons.health_and_safety,
    "ما يقال في اﻟﻤﺠلس": Icons.chair,
    "كفارة اﻟﻤﺠلس": Icons.do_not_touch,
    "الدعاء لمن قال غفر الله لك": Icons.how_to_reg,
    "الدعاء لمن صنع إليك معروفا": Icons.volunteer_activism,
    "ما يعصم الله به من الدجال": Icons.shield,
    "الدعاء لمن قال إني أحبك في الله": Icons.favorite,
    "الدعاء لمن عرض عليك ماله": Icons.account_balance_wallet,
    "الدعاء لمن أقرض عند القضاء": Icons.account_balance,
    "دعاء الخوف من الشرك": Icons.warning,
    "الدعاء لمن قال بارك الله فيك": Icons.how_to_reg,
    "دعاء كراهية الطيرة": Icons.remove_circle,
    "دعاء الركوب": Icons.directions_bus,
    "دعاء السفر": Icons.airplanemode_active,
    "دعاء دخول القرية أو البلدة": Icons.location_city,
    "دعاء دخول السوق": Icons.store,
    "الدعاء إذا تعس المركوب": Icons.directions_car,
    "دعاء المسافر للمقيم": Icons.people,
    "دعاء المقيم للمسافر": Icons.people_alt,
    "التكبير و التسبيح في سير السفر": Icons.north_east,
    "دعاء المسافر إذا أسحر": Icons.brightness_3,
    "الدعاء إذا نزل مترلا في سفر أو غيره": Icons.location_on,
    "ذكر الرجوع من السفر": Icons.arrow_back,
    "ما يقول من أتاه أمر يسره أو يكرهه": Icons.question_mark,
    "فضل الصلاة على النبي صلى الله عليه و سلم": Icons.favorite,
    "إفشاء السلام": Icons.handshake,
    "كيف يرد السلام على الكافر إذا سلم": Icons.handshake,
    "الدعاء عند سماع صياح الديك ونهيق الحمار": Icons.music_note,
    "دعاء نباح الكلب بالليل": Icons.pets,
    "الدعاء لمن سببته": Icons.warning,
    "ما يقول المسلم إذا مدح المسلم": Icons.thumb_up,
    "ما يقول المسلم إذا زكي": Icons.mood,
    "كيف يلبي المحرم في الحج أو العمرة ؟": Icons.temple_hindu,
    "التكبير إذا أتى الركن الأسود": Icons.flag,
    "الدعاء بين الركن اليماني والحجر الأسود": Icons.place,
    "دعاء الوقوف على الصفا والمروة": Icons.terrain,
    "الدعاء يوم عرفة": Icons.sunny,
    "الذكر عند المشعر الحرام": Icons.mosque,
    "التكبير عند رمي الجمار مع كل حصاة": Icons.circle,
    "دعاء التعجب والأمر السار": Icons.sentiment_satisfied,
    "ما يفعل من أتاه أمر يسره": Icons.check,
    "ما يقول عند الفزع": Icons.warning,
    "ما يقول عند الذبح أو النحر": Icons.food_bank,
    "ما يقول لرد كيد مردة الشياطين": Icons.cancel,
    "الاستغفار و التوبة": Icons.autorenew,
    "التسبيح، التحميد، التهليل، التكبير": Icons.star,
    "كيف كان النبي يسبح؟": Icons.menu_book,
    "من أنواع الخير والآداب الجامعة": Icons.group,
    "الرقية الشرعية من القرآن الكريم": Icons.book,
    "الرقية الشرعية من السنة النبوية": Icons.menu_book,
    "من تعار من الليل": Icons.nightlight_round,
    "أماكن وأوقات إجابة الدعاء": Icons.access_time,
  };
}

class AzkarEntity {
  final String title, description;
  final String content;
  final int count;

  AzkarEntity({
    required this.title,
    required this.description,
    required this.content,
    required this.count,
  });
}
